language: node_js
node_js:
  - '10'
scripts:
  - npm install codecov -g
after_success:
  - yarn test --coverage
  - codecov
deploy:
  provider: npm
  edge: true
  email: badgecrypto@gmail.com
  api_key:
    secure: 'aBkUuYpsv87d18A4UcUgRfzGdajsN+G3v58Fp1XI/XB22jfhlewRoobrPt740OJrOhjlPjsVMFfe6fA3mrOIYsqPkQ8EVpy24aL/yCHIJr4f9694FWC4uTBX8Uopb81q9bPfHlyk75FKFKgSFP2I6A2tSYwZcu4EOW5fQl7UfJ6Am7CYIM2VZb8A1+T7M+FJK7tlW8LrcYAhbC4La1492L9+KlpoIPSHbc5m8CcJyfXHPNFaGHsAzYzsMMBfOgkVmNmHooOiuJhkrKGUvzf/z3nPONWZyBzX3XXdrWY01u+RHDBHPYws669ITcKCELpH1et9GLuypESHyo0zE6oUY7vtMNZpzipC2lE/S777VaCtYSJc5EG5pXSPNeEWc0VuyXptINNmD2Gzk3P7eN5A1dXrIacrOV4BU1LQFCA5kx0IAdPDJTsde54S/H0apPRuMgva00yE7SQiDlfucGfF7DEv/INR5zx0kIfOQj76+QGpdZHDdbRP+P/XDgrGUaB9hMTXzhCfs18ZL+RPvFUQ2sMnj0NY3nSzriKYkYT0rzbGg6SLcsEwq0jT+qTSguVbLfNncJkmL7IEPPBWMShwr7TiSZc94sCJi1RE1WxAu3a2Qmjc00GLpRuiKsDppOg45/QZsiiv0PgyrZTfr7FCiCoBB5tBwX9FtPHo/z3szhU='
  on:
    tags: true
    branch: master
    repo: canfoundation/can-pass-verify
